### ISSUE TITLE
Handling of reviewaverage

### ISSUE THREAD

**Issue by JohHub** [AtriaStar/Atria#102]
Coming from #97, I don't know what would be the best way to store the reviewaverage. I'd love it to be a property in the wse model but you'd have to make sure it gets updated every time a review is added. On that note, I might be mistaken but it doesn't look like the Reviews property in the the wse model gets updated when a corresponding review gets added/deleted/changed.

**Comment by Saalvage** [comment]
Gonna look into this https://docs.microsoft.com/en-us/ef/core/performance/modeling-for-performance#update-cache-columns-when-inputs-change
