### ISSUE TITLE
One is able to access restricted pages

### ISSUE THREAD

**Issue by Jesicca1** [AtriaStar/Atria#113]
If you are not logged in, you can e.g. type"https://localhost:7206/settings" in the url and you will get on the settings page, despite someone who is not logged in should not be able to access the settings page

(sorry for bad english, english is not my first language)

**Comment by Saalvage** [comment]
Hello! I'm sorry to hear that you're having problems with using our software. Unfortunately, the applied labels are incorrect, as this is purely a front-end issue, I've adjusted them for you and someone will look into this as soon as possible.
Thank you for using Atria!
