### ISSUE TITLE
Bookmark icon inconsistent

### ISSUE THREAD

**Issue by Saalvage** [AtriaStar/Atria#167]
Button on list page
![image](https://user-images.githubusercontent.com/29021710/189730697-d1a73e9e-bc8b-4f2f-8602-d1d6b39e3b6c.png)

No button on detail page
![image](https://user-images.githubusercontent.com/29021710/189730732-28a046c7-f801-4e47-8880-519aa7516d05.png)

**Comment by JohHub** [comment]
fixed some time ago
