### ISSUE TITLE
tag logic on filter modal

### ISSUE THREAD

**Issue by Jesicca1** [AtriaStar/Atria#91]
Ablauf:
1.man öffnet das Filter-Modal
2.man wählt Tags aus
3.man geht auf anwenden -> Filter modal schließt sich
4.man öffnet das Filter Modal erneut -> die zuvor ausgewählten Tags sind bei der Liste nicht mehr blau markiert
5.man hält ctr gedrückt
6.man klickt auf einen Tag -> alle zuvor ausgewählten tags werden gelöscht

Das Problem (6.) hängt maybe mit dem (allein betrachtet unwichtigeren) Probelm aus 4. zusammen

https://translate.google.de/
https://www.leo.org/englisch-deutsch
https://www.urbandictionary.com/

**Comment by uwlnf** [comment]
6. hab ich unintentionally in meinem editWse_drafts branch gelöst
man muss jetzt nicht mal auf ctrl drücken
kannst ja mal ausprobieren
